[providers]
python = "3.9"

[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.build]

[start]
cmd = "python bot.py"

[variables]
PYTHONUNBUFFERED = "1"
